image: registry.gitlab.com/shrugal/wow-packager:latest

stages:
  - build
  - deploy

variables:
  RELEASE_TAGS: /^\d[\d\.]*(-(alpha|beta)\d+)?$/

build:
  stage: build
  only:
    - tags
    - web
  script:
    - release.sh -d
  artifacts:
    paths:
      - .release/PersoLootRoll/
      - .release/*.zip
  
curseforge:
  stage: deploy
  environment:
    name: CurseForge
    url: https://wow.curseforge.com/projects/persolootroll
  only:
    - $RELEASE_TAGS
  script:
    - release.sh -ocelzWHG

wowinterface:
  stage: deploy
  environment:
    name: WoWInterface
    url: https://www.wowinterface.com/downloads/info24667-PersoLootRoll.html
  only:
    - $RELEASE_TAGS
  script:
    - release.sh -ocelzLHG

github:
  stage: deploy
  environment:
    name: GitHub
    url: https://github.com/shrugal/PersoLootRoll/releases
  only:
    - $RELEASE_TAGS
  script:
    - release.sh -ocelzLWG

gitlab:
  stage: deploy
  environment:
    name: GitLab
    url: https://gitlab.com/shrugal/PersoLootRoll/releases
  only:
    - $RELEASE_TAGS
  script:
    - release.sh -ocelzLWH
